services:
  jwtpython:
    build:
      context: .
      args:
        JWT_VERSION: "3.4.0"
    image: jwtpython:fixed

    ports:
      - "8080:8080"

    mem_limit: 128m
    cpus: "0.5"
    pids_limit: 64
