[project]
name = "cve-2024-33664"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.127.0",
    "python-jose[cryptography]==3.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["jwtpython"]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "isort>=7.0.0",
]
