services:
  jwtgo:
    build: .
    image: jwtgo:dos

    ports:
      - "8080:8080"
      - "127.0.0.1:6060:6060"

    mem_limit: 128m
    cpus: "0.5"
    pids_limit: 64

    environment:
      GOMAXPROCS: "1"
      GOMEMLIMIT: "96MiB"
      SERVER_ADDR: "0.0.0.0"
